export const increment = () => ({ type: 'INCREMENT'})
export const decrement = () => ({ type: 'DECREMENT'})
export const start = () => ({ type: 'START' })
export const tick = () => ({ type: 'TICK' })
export const stop = () => ({ type: 'STOP' })
export const clear = () => ({ type: 'CLEAR' })